# -*- coding: utf-8 -*-
"""misclassified_images

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlvpHrPByApTvl7NaDtEFRPi4glbIpBt
"""

import matplotlib.pyplot as plt

def visualize_misclassified(filepath, regularizer, misclassified_imgs, misclassified_num=25):
  '''
  Function to visualize the misclassified images for a specific regularization option.

  :param regularizer: (string), specific regularization option
  :param misclassified_imgs: (list), list of misclassified images
  :param misclassified_num: (int), threshold for the number of misclassified images
  '''
  fig = plt.figure(figsize = (12, 8))
  for i in range(misclassified_num):
    ax = fig.add_subplot(5, 5, i+1, xticks=[], yticks=[])
    ax.imshow(misclassified_imgs[regularizer][i][0].cpu().squeeze(), cmap = 'gray')
    fig.suptitle(regularizer + ' Misclassified Images', fontsize = 12, y = 0.94)
    ax.set_title("Predicted-{} (Actual-{})".format(str(misclassified_imgs[regularizer][i][1].item()), str(misclassified_imgs[regularizer][i][2].item())), fontsize = 10)
  
    fig.savefig(filepath + '/EVA_figures/' + regularizer + '_misclassified_images.png');
