# -*- coding: utf-8 -*-
"""regularization.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJExzwodHo4AHU3AmqibEDmEVhE4WEnN
"""

# Imports
import torch

def weight_decay(model, loss, regularizer = 'WO_L1_L2', lamda1 = 0, lamda2 = 0):
  '''
  Function to apply different regularization options.
  
  :param model: (class), defined CNN model
  :param loss: (float), loss calculated from the loss function
  :param regularizer: (string), specific regularization option
  :param lamda1: (float), regularization coefficient for L1 loss
  :param lamda2: (float), regularization coefficient for L2 loss
  
  :returns: (float), loss calculated after adding regularization
  '''
  L1_loss = 0
  L2_loss = 0
  for params in model.parameters():  
    if regularizer == 'L1':
      L1_loss += torch.norm(params,1)
      loss += lamda1 * L1_loss
    elif regularizer == 'L2':
      L2_loss += torch.norm(params,2)
      loss += lamda2 * L2_loss
    elif regularizer == 'W_L1_L2':
      L1_loss += torch.norm(params,1)
      L2_loss += torch.norm(params,2)
      loss += lamda1*L1_loss + lamda2*L2_loss
    else:
      loss = loss 
  return loss